export const CATEGORIES = [
  {
    name: "Traditional wear",
    slug: "traditional",
    subcategories: [
      { name: "Panjabi — cotton",      slug: "panjabi-cotton" },
      { name: "Panjabi — silk",        slug: "panjabi-silk" },
      { name: "Panjabi — embroidered", slug: "panjabi-embroidered" },
      { name: "Pajama (for panjabi)",  slug: "pajama-panjabi" },
      { name: "Sherwani",              slug: "sherwani" },
      { name: "Kabli suit",            slug: "kabli-suit" },
      { name: "Fatua",                 slug: "fatua" },
    ],
  },
  {
    name: "T-shirts",
    slug: "t-shirts",
    subcategories: [
      { name: "Basic t-shirt",    slug: "tshirt-basic" },
      { name: "Printed t-shirt",  slug: "tshirt-printed" },
      { name: "Graphic t-shirt",  slug: "tshirt-graphic" },
      { name: "Polo t-shirt",     slug: "tshirt-polo" },
      { name: "Oversized t-shirt",slug: "tshirt-oversized" },
      { name: "Full sleeve t-shirt", slug: "tshirt-full-sleeve" },
    ],
  },
  {
    name: "Shirts",
    slug: "shirts",
    subcategories: [
      { name: "Formal shirt",     slug: "shirt-formal" },
      { name: "Casual shirt",     slug: "shirt-casual" },
      { name: "Check shirt",      slug: "shirt-check" },
      { name: "Denim shirt",      slug: "shirt-denim" },
      { name: "Linen shirt",      slug: "shirt-linen" },
      { name: "Half sleeve shirt",slug: "shirt-half-sleeve" },
      { name: "Full sleeve shirt",slug: "shirt-full-sleeve" },
    ],
  },
  {
    name: "Pants & bottom wear",
    slug: "pants",
    subcategories: [
      { name: "Jeans — slim fit",    slug: "jeans-slim" },
      { name: "Jeans — regular fit", slug: "jeans-regular" },
      { name: "Jeans — skinny",      slug: "jeans-skinny" },
      { name: "Gabardine pant",      slug: "pant-gabardine" },
      { name: "Formal pant",         slug: "pant-formal" },
      { name: "Chino pant",          slug: "pant-chino" },
      { name: "Cargo pant",          slug: "pant-cargo" },
      { name: "Jogger pant",         slug: "pant-jogger" },
      { name: "Shorts",              slug: "shorts" },
      { name: "Three-quarter pant",  slug: "pant-three-quarter" },
    ],
  },
  {
    name: "Winter wear",
    slug: "winter",
    subcategories: [
      { name: "Hoodie",     slug: "hoodie" },
      { name: "Sweatshirt", slug: "sweatshirt" },
      { name: "Sweater",    slug: "sweater" },
      { name: "Jacket",     slug: "jacket" },
      { name: "Blazer",     slug: "blazer" },
      { name: "Coat",       slug: "coat" },
    ],
  },
  {
    name: "Sports & active wear",
    slug: "sports",
    subcategories: [
      { name: "Tracksuit",       slug: "tracksuit" },
      { name: "Sports t-shirt",  slug: "sports-tshirt" },
      { name: "Gym wear",        slug: "gym-wear" },
      { name: "Jogging pant",    slug: "jogging-pant" },
      { name: "Compression wear",slug: "compression" },
    ],
  },
  {
    name: "Home & comfort wear",
    slug: "comfort",
    subcategories: [
      { name: "Night dress",  slug: "night-dress" },
      { name: "Pajama set",   slug: "pajama-set" },
      { name: "Loungewear",   slug: "loungewear" },
      { name: "Vest / sando", slug: "vest-sando" },
    ],
  },
  {
    name: "Formal & office wear",
    slug: "formal",
    subcategories: [
      { name: "Suit — 2-piece", slug: "suit-2piece" },
      { name: "Suit — 3-piece", slug: "suit-3piece" },
      { name: "Waistcoat",      slug: "waistcoat" },
      { name: "Tie & bow",      slug: "tie-bow" },
    ],
  },
  {
    name: "Kids boys wear",
    slug: "kids-boys",
    subcategories: [
      { name: "Baby set",     slug: "kids-baby-set" },
      { name: "Kids t-shirt", slug: "kids-tshirt" },
      { name: "Kids shirt",   slug: "kids-shirt" },
      { name: "Kids jeans",   slug: "kids-jeans" },
      { name: "Kids panjabi", slug: "kids-panjabi" },
    ],
  },
  {
    name: "Accessories",
    slug: "accessories",
    subcategories: [
      { name: "Cap",            slug: "cap" },
      { name: "Belt",           slug: "belt" },
      { name: "Socks",          slug: "socks" },
      { name: "Muffler / scarf",slug: "muffler-scarf" },
    ],
  },
];
